version: '3'
services:
  mysql:
    image: mysql/mysql-server:latest
    volumes:
      - ./.data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"