#!/usr/bin/env perl

use strict;
use warnings;
use lib qw/lib/;

BEGIN {
	$ENV{MOJO_MAX_MESSAGE_SIZE} = 2 * 1024 * 1024 * 1024; # 2 GB
}

# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('Phonebook');
